"""empty message

Revision ID: 062449660793
Revises: 56284858aa23
Create Date: 2023-10-25 17:52:49.873619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062449660793'
down_revision = '56284858aa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
